//
// Vehicle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Vehicle: Codable {

    public var _id: Int64
    public var name: String
    public var brand: String
    public var model: String
    public var year: Int
    public var vin: String?
    public var licensePlate: String?
    public var purchaseDate: Date?
    public var image: String?
    public var odometer: Int
    public var createdAt: Date?
    public var updatedAt: Date?
    public var events: [VEvent]?

    public init(_id: Int64, name: String, brand: String, model: String, year: Int, vin: String? = nil, licensePlate: String? = nil, purchaseDate: Date? = nil, image: String? = nil, odometer: Int, createdAt: Date? = nil, updatedAt: Date? = nil, events: [VEvent]? = nil) {
        self._id = _id
        self.name = name
        self.brand = brand
        self.model = model
        self.year = year
        self.vin = vin
        self.licensePlate = licensePlate
        self.purchaseDate = purchaseDate
        self.image = image
        self.odometer = odometer
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.events = events
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case brand
        case model
        case year
        case vin
        case licensePlate
        case purchaseDate
        case image
        case odometer
        case createdAt
        case updatedAt
        case events
    }

}
