//
// VEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VEvent: Codable {

    public var _id: Int64
    public var title: String
    public var amount: Double?
    public var quantity: Int?
    public var _description: String?
    public var location: String?
    public var recordedDate: Date
    public var recordedMileage: Int
    public var upcomingDate: Date
    public var upcomingMileage: Int
    public var completedDate: Date?
    public var completedMileage: Int?
    public var isCompleted: Bool?
    public var vehicle: Vehicle

    public init(_id: Int64, title: String, amount: Double? = nil, quantity: Int? = nil, _description: String? = nil, location: String? = nil, recordedDate: Date, recordedMileage: Int, upcomingDate: Date, upcomingMileage: Int, completedDate: Date? = nil, completedMileage: Int? = nil, isCompleted: Bool? = nil, vehicle: Vehicle) {
        self._id = _id
        self.title = title
        self.amount = amount
        self.quantity = quantity
        self._description = _description
        self.location = location
        self.recordedDate = recordedDate
        self.recordedMileage = recordedMileage
        self.upcomingDate = upcomingDate
        self.upcomingMileage = upcomingMileage
        self.completedDate = completedDate
        self.completedMileage = completedMileage
        self.isCompleted = isCompleted
        self.vehicle = vehicle
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case amount
        case quantity
        case _description = "description"
        case location
        case recordedDate
        case recordedMileage
        case upcomingDate
        case upcomingMileage
        case completedDate
        case completedMileage
        case isCompleted
        case vehicle
    }

}
